[package]
name = "hs_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
hs_gba = { path = "../hs_gba/" }
hs_dbg = { path = "../hs_dbg/" }
crossbeam = "0.8.2"
ctrlc = "3.2.4"
lazy_static = "1.4.0"
